rules rewrite,  closes #146
sopra-fs23-group-37/client pull request #153
Opened 2023-05-07 08:50 UTC by carolernst-uzh

2023-05-07 19:15 UTC, bbajrari commented on src/components/views/Rulebook.js
> +                    <strong>2 of Clubs</strong>, the{" "}
add a space between `the` & `2`

2023-05-07 19:20 UTC, bbajrari requested changes
Add the space according to the commentary on line `138`. Otherwise you're good to go. Very good job!

2023-05-08 07:43 UTC, carolernst-uzh commented on src/components/views/Rulebook.js
> +                    <strong>2 of Clubs</strong>, the{" "}
@bbajrari added the space, thanks for catching that!

2023-05-08 11:43 UTC, bbajrari approved these changes

2023-05-08 11:53 UTC, merged